### ISSUE TITLE
redeploy needed 

### ISSUE THREAD

**Issue by marc115uk** [3ative/HA-Alexa#1]
Any idea how to work with context? I have to keep redeploying my node red flow to get it to work again, sometimes multiple times a day, I have added the following in settings.js 
contextStorage: {
   default: {
       module: "localfilesystem"
   }
} 
yet I am still having to redeploy quite often. I am guessing I need to do more but unsure what. Any help would be great thanks

**Comment by 3ative** [comment]
"context" is too broad of a term. I'd need more info to understand your issue.

**Comment by marc115uk** [comment]
So I will say Alexa turn on Tv and she will ping like she has done it, however nothing will happen. I go into node red and move a node so I can hit deploy and she will work again fine, for a few hours- a day or 2 then will stop working again until I redeploy again. 
Thought it may have been this issue but maybe not? 

"Device settings are reset after Node-Red restart

Amazon Echo Hub uses Node-RED context feature to store device settings. By default, context is stored in memory only. In order to preserve the device settings after restart context storage has to be changed to localfilesystem. Local File System Context"

**Comment by 3ative** [comment]
OIC... I haven't noticed the same here. This sounds like an issue for the "**node-red-contrib-amazon-echo**" and not my code/example/tutorial.
- I see you've opened-closed-re-opened an issue there already. So, I'll close this one.
